const thoughts = [
    "Happiness is a choice.",
    "Every journey begins with a single step.",
    "Be the change you wish to see in the world.",
    "In the end, we only regret the chances we didn't take.",
    "Life is too short to hold grudges.",
    "Success is not final, failure is not fatal: It is the courage to continue that counts.",
    "The best way to predict the future is to create it.",
    "Kindness costs nothing but means everything.",
    "Don't wait for opportunity, create it.",
    "You are the author of your own story.",
    "The only way to do great work is to love what you do.",
    "Challenges are what make life interesting.",
    "Do what you can, with what you have, where you are.",
    "Dream big, work hard, stay focused, and surround yourself with good people.",
    "Your attitude determines your direction.",
    "The journey of a thousand miles begins with a single step.",
    "Don't let the fear of striking out keep you from playing the game.",
    "Today is a gift. That's why it's called the present.",
    "Success is not about the destination, it's about the journey.",
    "Happiness is found when you stop comparing yourself to others.",
    "Believe you can and you're halfway there.",
    "Life is short, make it sweet.",
    "Opportunities don't happen, you create them.",
    "The only limit is the one you set for yourself.",
    "Don't look back, you're not going that way.",
    "Change your thoughts and you'll change your world.",
    "Success is stumbling from failure to failure with no loss of enthusiasm.",
    "Life is a series of moments. Make each one count.",
    "The secret of getting ahead is getting started.",
    "Every day is a chance to be better than yesterday.",
  ];


  const reactions = [
    "Wow!",
    "Amazing!",
    "Incredible!",
    "Brilliant!",
    "Impressive!",
    "Fantastic!",
    "Great job!",
    "You're awesome!",
    "Well done!",
    "Outstanding!",
    "Excellent!",
    "Superb!",
    "Marvelous!",
    "Terrific!",
    "Perfect!",
    "Keep it up!",
    "Wonderful!",
    "Inspiring!",
    "You nailed it!",
    "You rock!",
    "So proud of you!",
    "Nice work!",
    "You're a star!",
    "Fantastic effort!",
    "Bravo!",
    "That's incredible!",
    "Thumbs up!",
    "You're on fire!",
    "Outstanding work!",
  ];

  const names = [
    'Aaran',
    'Aaren',
    'Aarez',
    'Aarman',
    'Aaron',
    'Aaron-James',
    'Aarron',
    'Aaryan',
    'Aaryn',
    'Aayan',
    'Aazaan',
    'Abaan',
    'Abbas',
    'Abdallah',
    'Abdalroof',
    'Abdihakim',
    'Abdirahman',
    'Abdisalam',
    'Abdul',
    'Abdul-Aziz',
    'Abdulbasir',
    'Abdulkadir',
    'Abdulkarem',
    'Smith',
    'Jones',
    'Coollastname',
    'enter_name_here',
    'Ze',
    'Zechariah',
    'Zeek',
    'Zeeshan',
    'Zeid',
    'Zein',
    'Zen',
    'Zendel',
    'Zenith',
    'Zennon',
    'Zeph',
    'Zerah',
    'Zhen',
    'Zhi',
    'Zhong',
    'Zhuo',
    'Zi',
    'Zidane',
    'Zijie',
    'Zinedine',
    'Zion',
    'Zishan',
    'Ziya',
    'Ziyaan',
    'Zohaib',
    'Zohair',
    'Zoubaeir',
    'Zubair',
    'Zubayr',
    'Zuriel',
    'Xander',
    'Jared',
    'Courtney',
    'Gillian',
    'Clark',
    'Jared',
    'Grace',
    'Kelsey',
    'Tamar',
    'Alex',
    'Mark',
    'Tamar',
    'Farish',
    'Sarah',
    'Nathaniel',
    'Parker',
  ];

  const getRandomArrItem = (arr) => arr[Math.floor(Math.random() * arr.length)];

  const getRandomThought = () =>
  `${getRandomArrItem(thoughts)} ${getRandomArrItem(thoughts)}`;

  const getRandomName = () =>
  `${getRandomArrItem(names)} ${getRandomArrItem(names)}`;

  const getRandomReactions = (int) => {
    const results =[]
    for(let i =0; i< int; i++){
        results.push({
            reactionBody: getRandomArrItem(reactions),
            username: getRandomName()
    });
    }

    return results;
  }

  module.exports = { getRandomReactions,getRandomThought, getRandomName};